export * from './IAddAccount';
export * from './IAuthentication';
export * from './ILoadAccountByToken';
export * from './IAddSurvey';
export * from './ILoadAnswersBySurvey';
export * from './ICheckSurveyById';
export * from './ILoadSurveys';
export * from './ILoadSurveyResult';
export * from './ISaveSurveyResult';
